version: "3"
services:
  mysql8:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3318:3306"
    command: "--ssl"
    # command: "--default-authentication-plugin=mysql_native_password"
    restart: always
  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3317:3306"
    # command: "--default-authentication-plugin=mysql_native_password"
    restart: always
  mysql56:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3316:3306"
    # command: "--default-authentication-plugin=mysql_native_password"
    restart: always
